### ISSUE TITLE
Errors when run in ISE

### ISSUE THREAD

**Issue by GavinEke** [SteveLowe/SLMenu#1]
When running in the ISE I get the following error.

```
-- Test Menu ----------------------------------------------------------------------------------
--- Write-Host : Cannot process the color because -1 is not a valid color.
Parameter name: value
Actual value was -1.
At C:\Users\gavine\Documents\WindowsPowerShell\Modules\SLMenu\SLMenu.ShowMenu.psm1
:361 char:13
+             Write-Host "$($MenuItem.Key): $($MenuItem.Name)" -NoNewLi ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Write-Host], ArgumentOutOfRan 
   geException
    + FullyQualifiedErrorId : SetInvalidForegroundColor,Microsoft.PowerShell.Comm 
   ands.WriteHostCommand
```

I am running Windows 10 x64 haven't tested other machines but it works when running from the ConsoleHost. The code is just from your README.md under the `Menu` heading.

**Comment by GavinEke** [comment]
I tried to work around this but it heavily relies on `$host` it might be worth adding `PowerShellHostName = ‘ConsoleHost’` to SLMenu.psd1 or even just a write warning that it will not work in the ISE.

Eg.

```
if (Get-Host | Where {$_.Name -like "*ISE*"}) {
    Write-Warning "SLMenu cannot be run from the ISE"
}
```

**Comment by SteveLowe** [comment]
Thanks for the feedback.

I did actually have PowerShellHostName set, but removed it at the last second to get appveyor to run pester.
I'm gonna expand on your second choice: 
Write-Warning on Import-Module, and Write-Error on Show-SLMenu.

It is unfortunate that I have to rely on $Host, which doesn't work the same in the ISE. To the best of my knowledge there is no other way to get this kind of functionality in Powershell.
